name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: '🚀 Features'
    labels:
      - '🚀 Feature'
      - '♻️ Refactor'
  - title: '🐛 Bug Fixes'
    label: '🐛 BugFix'
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
  template: |
  ## 📋 변경점
  
  $CHANGES
