name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: 
      - "🚀 Feature"
      - "♻️ Refactor"
  - title: "🐛 Bug Fixes"
    labels: 
      - "🐛 BugFix"
exclude-labels:
  - "✅ Test"
  - "🛠 Setting"
template: |
  ## 📋 변경점
  $CHANGES
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
change-template: "- $TITLE (#$NUMBER)"
