name: Slack alert for main branch

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - name: 의도적 실패 유발
    #   run: exit 1
    
    - name: 배포 성공 알림 발송
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: 배포 ${{ job.status == 'success' && '성공' || '실패' }}
        fields: repo, commit, message, author
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
