name: Discord alert for main branch

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # - name: 의도적 실패 유발
    #   run: exit 1
    
    - name: 배포 성공 알림 발송
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        status: ${{ job.status }}
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: 배포 ${{ job.status == 'success' && '성공' || '실패' }}
        avatar_url: ${{ secrets.MILLICON_AVATAR_URL }}
        username: GitHub Actions
        color: ${{ job.status == 'success' && 0x009900 || 0xff0000 }}
