name: Scheduled Jobs

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: echo repository name
        run: echo "${{ github.repository }}"
      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: githubActionsTest

      - name: run script
        run: |
          cd githubActionsTest
          date >> date.txt
          git add .
          git config --global user.email "agsooho0303@gmail.com"
          git config --global user.name "angelSooho"
          git commit -am "Inject Date"
          git push
